image: elixir:1.8.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - deps
    - _build

stages:
  - lint
  - test
  - analysis

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile --force

lint:
  stage: lint
  script:
    - mix format --check-formatted

unit-testing:
  stage: test
  coverage: '/(\d+\.\d+\%) \| Total/'
  script:
    - mix test --trace --cover

analysis:
  stage: analysis
  script:
    - mix credo --strict
